# Generated by Django 4.2 on 2023-04-12 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinspinapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coinmaster',
            name='detial',
        ),
        migrations.AddField(
            model_name='coinmaster',
            name='detail',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coinmaster',
            name='link',
            field=models.URLField(unique=True),
        ),
        migrations.AlterField(
            model_name='coinmaster',
            name='title',
            field=models.CharField(blank=True, default=' ', max_length=255),
            preserve_default=False,
        ),
    ]
