# Generated by Django 4.2 on 2023-04-13 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinspinapp', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='sno',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
