# Generated by Django 4.2 on 2023-04-12 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coinspinapp', '0002_remove_coinmaster_detial_coinmaster_detail_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coinmaster',
            name='link',
            field=models.URLField(),
        ),
    ]
